language: minimal

sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - $HOME/.stack-lts-7.22
    - $HOME/.stack-ghc-8.2.1
    - .stack

# We test against different Stackage snapshots.
env:
  - BUILD=stack STACK_YAML=stack.yaml STACK_ROOT=$HOME/.stack
  - BUILD=stack STACK_YAML=stack-lts-7.22.yaml STACK_ROOT=$HOME/.stack-lts-7.22
  - BUILD=stack STACK_YAML=stack-ghc-8.2.1.yaml STACK_ROOT=$HOME/.stack-ghc-8.2.1

addons:
  apt:
    sources:
      - sourceline: 'ppa:adrozdoff/emacs'
    packages:
    - hlint
    - python
    - python-numpy
    - libgmp-dev
    - emacs25

jobs:
  include:
  - stage: build
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - ./.travis-setup.sh
    - stack build --fast alex happy
    - stack --no-terminal test --fast --only-dependencies -j 3
    - stack --no-terminal build -j 3
  - stage: test
    script:
    - stack test
    - stack install
    # Now for integration testing
    - futhark-test --nobuffer tests examples # Run integration test suite.
    # Numpy is broken on Travis in a weird way I can't reproduce anywhere else.
    # - futhark-test tests examples --compiler=futhark-py --exclude=no_python -c # Run integration test suite with Python code generator.

    # Check for style issues.
    - if [ "$STACK_YAML" = stack.yaml ]; then
        stack install hlint --fast && tools/style-check.sh src;
      fi

    # Check the automatic indentation feature of the futhark-mode.el Emacs
    # editing mode.
    - if [ "$STACK_YAML" = stack.yaml ]; then
        emacs --version;
        cd tools && ./futhark-mode.el-corpus-test.sh;
      fi

# EOF
